### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by andela-sjames**

### CODE REVIEW

**Comment by andela-sjames** [comment]
@elo80ka you can clone the repository and run setup.py to have the latest build on your system. While I update the package index.

**Comment by elo80ka** [comment]
I'm currently installing directly from git using pip. I'll update my
requirements.txt once you release to PyPI.

Cheers!


On 25 Apr 2017 3:43 pm, "andela-sjames" <notifications@github.com> wrote:

@elo80ka <https://github.com/elo80ka> you can clone the repository and run
setup.py to have the latest build on your system. While I update the
package index.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/andela-sjames/paystack-python/pull/31#issuecomment-297052975>,
or mute the thread

**Comment by andela-sjames** [comment]
@elo80ka give me a moment will update the module now

**Comment by andela-sjames** [comment]
@elo80ka updated https://pypi.python.org/pypi/paystackapi/1.2.5

**Pull request merged**
